server:
  port: ${ADMIN_PORT:8765}

spring:
  application:
    name: ${ADMIN_APP_NAME:admin-service}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost